core/urls.py
from django.urls import path
from core.views import (
    CancelOrderView,
    CreateOrderView,
    FetchOrderView,
    FetchUserOrdersView,
    PaymentCallbackView,
    ProductView,
    ProductsView,
    ProductReservationView,
    ProductSearchView,
)

app_name = "core"

urlpatterns = [
    path("product/", ProductsView.as_view(), name="products"),
    path("product/<int:id>/", ProductView.as_view(), name="one_product"),
    path("product/reservation/", ProductReservationView.as_view(), name="product_reservation"),
    path("product/search/", ProductSearchView.as_view(), name="product_search"),
    path("payment-callback/", PaymentCallbackView.as_view(), name="payment_callback"),
    path("order/", FetchUserOrdersView.as_view(), name="user_orders"),
    path("order/cancel/", CancelOrderView.as_view(), name="cancel_order"),
    path("order/create/", CreateOrderView.as_view(), name="create_order"),
    path("order/<str:id>/", FetchOrderView.as_view(), name="fetch_order"),
]

seller_dashboard/urls.py
from functools import wraps

from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import path

from seller_dashboard.views import (
    DashboardView,
    OrderDetailForAdminView
)


def staff_required(func):
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        current_user = request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            return func(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)
    return wrapper


app_name = "seller_dashboard"

urlpatterns = [
    path("", staff_required(DashboardView.as_view()), name="dashboard"),
    path("order/<str:pk>/", staff_required(OrderDetailForAdminView.as_view()), name="order_detail"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

from shop.api_documentation import schema_view

urlpatterns = [
    path("api-docs/", schema_view.with_ui('swagger', cache_timeout=0), name='schema_swagger_ui'),
    path("redoc/", schema_view.with_ui('redoc', cache_timeout=0), name='schema_redoc'),

    path("admin/", admin.site.urls),
    path("seller-dashboard/", include('seller_dashboard.urls', namespace='seller_dashboard')),

    path("api/auth/", include('authentication.urls', namespace='auth')),
    path("api/shop/", include('core.urls')),
]

core/models.py
from django.db import models
from django.utils import timezone
from jsonfield.fields import JSONField


class Product(models.Model):
    title = models.CharField(max_length=255, unique=True)
    image = models.CharField(max_length=255, blank=True, null=True)
    price = models.IntegerField(default=1)
    quantity = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Order(models.Model):
    IN_PROGRESS = "in_progress"
    PAID = "paid"
    COMPLETED = "completed"
    CANCELED = "canceled"

    ORDER_STATUS = [
        (IN_PROGRESS, "In Progress"),
        (PAID, "Paid"),
        (COMPLETED, "Completed"),
        (CANCELED, "Canceled"),
    ]

    id = models.CharField(primary_key=True, max_length=65, unique=True)
    buyer = models.ForeignKey("authentication.User", on_delete=models.SET_NULL, null=True)
    buyer_email = models.EmailField()
    buyer_name = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    delivery_address = models.CharField(max_length=255, blank=True, null=True)
    delivery_date = models.DateField(blank=True, null=True)
    delivery_time = models.TimeField(blank=True, null=True)
    total = models.SmallIntegerField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default=IN_PROGRESS)
    products = JSONField(default=list)
    payment_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"User: {self.buyer_email}, Order: {self.id[:8]}"

    def save(self, *args, **kwargs):
        """
        Handler order status change and update product quantities.

        This method intercepts the save operation for an Order instance.
        When an existing order is saved with a change in its 'status' field
        to 'CANCELED', it triggers an update to the product quantities to
        revert the reserved quantities for canceled items.
        """
        if self.pk:
            try:
                original_order = Order.objects.get(id=self.pk)
                if original_order.status != self.status and self.status == Order.CANCELED:
                    self._update_product_quantity(original_order.products)
            except:
                pass
        super().save(*args, **kwargs)

    def _update_product_quantity(self, products):
        """
        Updates the quantity of products after order cancellation.
        """
        product_ids = [item["id"] for item in products]
        products_amount = {item["id"]: item["amount"] for item in products}
        products_to_update = []
        for product in Product.objects.filter(id__in=product_ids):
            products_to_update.append(Product(
                id=product.id,
                quantity=product.quantity + products_amount[product.id]
            ))
        Product.objects.bulk_update(products_to_update, ["quantity"])

seller_dashboard/views.py
"""These views use only HTMX."""

from django.views.generic import DetailView, ListView
from core.models import Order


class DashboardView(ListView):
    template_name = 'seller_dashboard/dashboard.html'
    context_object_name = 'orders'
    paginate_by = 20

    def get_queryset(self):
        self.status = self.request.GET.get('status', None)
        sort = self.request.GET.get('sort', 'created_at')
        orders = Order.objects.all()
        if self.status:
            orders = orders.filter(status=self.status)
        return orders.order_by(sort)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.headers.get('HX-Request'):
            self.template_name = 'seller_dashboard/orders_list_data.html'
        return context


class OrderDetailForAdminView(DetailView):
    model = Order
    template_name = 'seller_dashboard/order_detail.html'
    context_object_name = 'order'

seller_dashboard/templates/seller_dashboard/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {
                font-family: 'Arial', sans-serif;
                background-color: #f8f9fa;
            }
            header {
                background-color: #343a40;
                padding: 10px 0;
            }
            header nav a {
                color: #ffffff;
                text-decoration: none;
                padding: 15px 20px;
                display: inline-block;
            }
            header nav a:hover {
                background-color: #495057;
            }
            main {
                padding: 20px;
            }
            .custom-nav-tabs {
                display: flex;
                justify-content: space-between;
                flex-wrap: wrap;
                border-bottom: none;
                padding: 0;
                margin: 0;
            }

            .custom-nav-tabs .nav-item {
                flex: 1;
                text-align: center;
                list-style: none;
            }

            .custom-nav-tabs .nav-link {
                color: #495057;
                background-color: #f8f9fa;
                border: none;
                font-weight: bold;
                padding: 10px;
                border-radius: 5px;
                transition: background-color 0.3s, color 0.3s;
                display: block;
            }

            .custom-nav-tabs .nav-link.active {
                background-color: #343a40;
                color: #ffffff;
            }

            .custom-nav-tabs .nav-link:hover {
                background-color: #495057;
                color: #ffffff;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://unpkg.com/htmx.org@1.7.0"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const filterButton = document.getElementById('apply-filter');
                const loadMoreButton = document.getElementById('load-more');
                const statusFilter = document.getElementById('status-filter');
                const sortFilter = document.getElementById('sort-filter');

                filterButton.addEventListener('click', function() {
                    const selectedStatus = statusFilter.value;
                    const selectedSortField = sortFilter.value;
                    const url = new URL("{% url 'seller_dashboard:dashboard' %}", window.location.origin);

                    if (selectedStatus !== "all")  url.searchParams.set('status', selectedStatus);
                    if (selectedSortField !== "") url.searchParams.set('sort', selectedSortField);

                    htmx.ajax('GET', url.toString(), {target: '.orders-list'});
                });
            });
        </script>
    </head>
    <body>
        <header>
            <nav class="container">
                <a href="http://{{ FRONTEND_HOST }}">Home</a>
                <a href="{% url 'seller_dashboard:dashboard' %}">Dashboard</a>
                {% if user.is_authenticated and user.is_superuser %}
                    <a href="{% url 'admin:index' %}">Admin Panel</a>
                {% endif %}
            </nav>
        </header>
        <main class="container">
            {% block content %}{% endblock %}
        </main>
    </body>
</html>

seller_dashboard/templates/seller_dashboard/dashboard.html
{% extends 'seller_dashboard/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Dashboard</h1>
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <label for="status-filter" class="form-label mb-1">Status</label>
                        <select id="status-filter" class="form-select">
                            <option value="all">All</option>
                            <option value="in_progress">In Progress</option>
                            <option value="paid">Paid</option>
                            <option value="completed">Completed</option>
                            <option value="canceled">Canceled</option>
                        </select>
                        <label for="sort-filter" class="form-label mb-1">Sort by</label>
                        <select id="sort-filter" class="form-select">
                            <option value="" selected>-----</option>
                            <option value="buyer_name">Buyer</option>
                            <option value="created_at">Created At</option>
                            <option value="payment_at">Payment At</option>
                            <option value="total">Total</option>
                        </select>
                        <button type="button" id="apply-filter" class="btn btn-primary">Filter</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div hx-trigger="load">
        {% include 'seller_dashboard/orders_list_base.html' %}
    </div>
</div>

<!-- Modal window for order details -->
<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="orderModalLabel">Order Details</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="order-details">
            </div>
        </div>
    </div>
</div>

{% endblock %}

seller_dashboard/templates/seller_dashboard/order_detail.html
<div>
    <p>Order ID: <b>{{ order.id | truncatechars:10 }}</b></p>
    <p>Status: <b>{{ order.get_status_display }}</b></p>
    <p>Total: <b>{{ order.total | default:"-" }}</b></p>
    <p>Created at: <b>{{ order.created_at }}</b></p>
    <p>Payment at: <b>{{ order.payment_at | default:"-" }}</b></p>
    </br>
    <h5>Buyer details</h5>
    <p>Name: {{ order.buyer_name }}</p>
    <p>Email: {{ order.buyer_email }}</p>
    <p>Phone: {{ order.phone }}</p>
    <p>Address: {{ order.delivery_address }}</p>
    </br>
    <h5>Delivery Time</h5>
    <p>{{ order.delivery_date|default:"-" }} at {{ order.delivery_time|default:"-" }}</p>
    </br>
    <h5>Products included in the order</h5>
    <table border="1" cellpadding="10" cellspacing="0" width="100%">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Amount</th>
        </tr>
        {% for product in order.products %}
            <tr>
                <td>{{ product.id | truncatechars:7 }}</td>
                <td>{{ product.title }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.quantity }}</td>
                <td>{{ product.amount }}</td>
            </tr>
        {% endfor %}
    </table>
</div>

seller_dashboard/templates/seller_dashboard/orders_list_base.html
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Buyer</th>
            <th scope="col">Created At</th>
            <th scope="col">Payment At</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody class="orders-list">
        {% include 'seller_dashboard/orders_list_data.html' %}
    </tbody>
</table>

<!-- Pagination -->
{% if page_obj.has_next %}
<div class="d-flex justify-content-center mt-4">
    <button id="load-more" class="btn btn-primary"
        hx-get="?page={{ page_obj.next_page_number }}"
        hx-target=".orders-list" hx-swap="beforeend"
        hx-on="htmx:afterRequest: this.remove()"
    >
        Load more
    </button>
</div>
{% endif %}

seller_dashboard/templates/seller_dashboard/orders_list_data.html
{% for order in orders %}
<tr 
    hx-get="{% url 'seller_dashboard:order_detail' order.id %}"
    hx-trigger="click"
    hx-target="#order-details"
    hx-swap="innerHTML"
    data-toggle="modal"
    data-target="#orderModal"
>
    <td>{{ order.buyer_name }}</td>
    <td>{{ order.created_at }}</td>
    <td>{{ order.payment_at | default:"-" }}</td>
    <td>{{ order.total | default:"-" }}</td>
    <td>{{ order.get_status_display }}</td>
</tr>
{% endfor %}